/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_newline = 2,
  sym_comment = 3,
  anon_sym_COLON = 4,
  anon_sym_COMMA = 5,
  sym_mnemonic = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_PLUS = 9,
  anon_sym_DASH = 10,
  sym_directive_name = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_TILDE = 14,
  anon_sym_PIPE = 15,
  anon_sym_AMP = 16,
  anon_sym_LT_LT = 17,
  anon_sym_GT_GT = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  sym_register = 21,
  sym_number = 22,
  anon_sym_DQUOTE = 23,
  sym__string_content = 24,
  sym_escape_sequence = 25,
  sym_preproc_arg = 26,
  aux_sym_preproc_include_token1 = 27,
  aux_sym_preproc_error_token1 = 28,
  aux_sym_preproc_define_token1 = 29,
  aux_sym_preproc_undef_token1 = 30,
  aux_sym_preproc_if_token1 = 31,
  aux_sym_preproc_if_token2 = 32,
  aux_sym_preproc_elif_token1 = 33,
  aux_sym_preproc_else_token1 = 34,
  sym_source_file = 35,
  sym__item = 36,
  sym__line_content = 37,
  sym__code_line = 38,
  sym__statement = 39,
  sym_label = 40,
  sym_instruction = 41,
  sym__operand = 42,
  sym_direct = 43,
  sym_indirect = 44,
  sym_indexed = 45,
  sym_directive = 46,
  sym__expression = 47,
  sym_parenthesized_expression = 48,
  sym_unary_expression = 49,
  sym_binary_expression = 50,
  sym_string = 51,
  sym_preproc_include = 52,
  sym_preproc_error = 53,
  sym_preproc_define = 54,
  sym_preproc_undef = 55,
  sym_preproc_if = 56,
  sym_preproc_elif = 57,
  sym_preproc_else = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym__code_line_repeat1 = 60,
  aux_sym_instruction_repeat1 = 61,
  aux_sym_string_repeat1 = 62,
  aux_sym_preproc_if_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [sym_mnemonic] = "mnemonic",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_directive_name] = "directive_name",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_TILDE] = "~",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_register] = "register",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_content] = "_string_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_preproc_arg] = "preproc_arg",
  [aux_sym_preproc_include_token1] = "preproc_directive",
  [aux_sym_preproc_error_token1] = "preproc_directive",
  [aux_sym_preproc_define_token1] = "preproc_directive",
  [aux_sym_preproc_undef_token1] = "preproc_directive",
  [aux_sym_preproc_if_token1] = "preproc_directive",
  [aux_sym_preproc_if_token2] = "preproc_directive",
  [aux_sym_preproc_elif_token1] = "preproc_directive",
  [aux_sym_preproc_else_token1] = "preproc_directive",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym__line_content] = "_line_content",
  [sym__code_line] = "_code_line",
  [sym__statement] = "_statement",
  [sym_label] = "label",
  [sym_instruction] = "instruction",
  [sym__operand] = "_operand",
  [sym_direct] = "direct",
  [sym_indirect] = "indirect",
  [sym_indexed] = "indexed",
  [sym_directive] = "directive",
  [sym__expression] = "_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [sym_preproc_include] = "preproc_include",
  [sym_preproc_error] = "preproc_error",
  [sym_preproc_define] = "preproc_define",
  [sym_preproc_undef] = "preproc_undef",
  [sym_preproc_if] = "preproc_if",
  [sym_preproc_elif] = "preproc_elif",
  [sym_preproc_else] = "preproc_else",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__code_line_repeat1] = "_code_line_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_preproc_if_repeat1] = "preproc_if_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_mnemonic] = sym_mnemonic,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_directive_name] = sym_directive_name,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_register] = sym_register,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_content] = sym__string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_preproc_arg] = sym_preproc_arg,
  [aux_sym_preproc_include_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_error_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_define_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_undef_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_if_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_if_token2] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_elif_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_else_token1] = aux_sym_preproc_include_token1,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym__line_content] = sym__line_content,
  [sym__code_line] = sym__code_line,
  [sym__statement] = sym__statement,
  [sym_label] = sym_label,
  [sym_instruction] = sym_instruction,
  [sym__operand] = sym__operand,
  [sym_direct] = sym_direct,
  [sym_indirect] = sym_indirect,
  [sym_indexed] = sym_indexed,
  [sym_directive] = sym_directive,
  [sym__expression] = sym__expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [sym_preproc_include] = sym_preproc_include,
  [sym_preproc_error] = sym_preproc_error,
  [sym_preproc_define] = sym_preproc_define,
  [sym_preproc_undef] = sym_preproc_undef,
  [sym_preproc_if] = sym_preproc_if,
  [sym_preproc_elif] = sym_preproc_elif,
  [sym_preproc_else] = sym_preproc_else,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__code_line_repeat1] = aux_sym__code_line_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_preproc_if_repeat1] = aux_sym_preproc_if_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_mnemonic] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_include_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_error_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_define_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_undef_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_if_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_if_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_elif_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_else_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym__line_content] = {
    .visible = false,
    .named = true,
  },
  [sym__code_line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym_direct] = {
    .visible = true,
    .named = true,
  },
  [sym_indirect] = {
    .visible = true,
    .named = true,
  },
  [sym_indexed] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_include] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_error] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_define] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_undef] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_if] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_elif] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_else] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__code_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preproc_if_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_condition = 2,
  field_left = 3,
  field_message = 4,
  field_mnemonic = 5,
  field_name = 6,
  field_operand = 7,
  field_operator = 8,
  field_path = 9,
  field_right = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_condition] = "condition",
  [field_left] = "left",
  [field_message] = "message",
  [field_mnemonic] = "mnemonic",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_path] = "path",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 3},
  [10] = {.index = 14, .length = 1},
  [11] = {.index = 15, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_mnemonic, 0},
  [1] =
    {field_argument, 1},
    {field_name, 0},
  [3] =
    {field_name, 0},
  [4] =
    {field_path, 1},
  [5] =
    {field_message, 1},
  [6] =
    {field_name, 1},
  [7] =
    {field_operand, 1},
    {field_operator, 0},
  [9] =
    {field_name, 1},
    {field_value, 2},
  [11] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [14] =
    {field_condition, 1},
  [15] =
    {field_operator, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '"', 86,
        '#', 9,
        '%', 50,
        '&', 75,
        '(', 71,
        ')', 72,
        '*', 78,
        '+', 68,
        ',', 65,
        '-', 69,
        '.', 38,
        '/', 79,
        '0', 81,
        ':', 64,
        '<', 6,
        '>', 7,
        '[', 66,
        '\\', 3,
        ']', 67,
        '|', 74,
        '~', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(91);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(86);
      if (lookahead == '/') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(90);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(76);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(77);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(98);
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(100);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(99);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(21);
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 37:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(93);
      END_STATE();
    case 38:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(43);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(51);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(49);
      END_STATE();
    case 39:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(80);
      END_STATE();
    case 41:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 42:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(70);
      END_STATE();
    case 43:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 44:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(53);
      END_STATE();
    case 45:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 46:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 48:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 49:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(40);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(56);
      if (lookahead == 'A' ||
          lookahead == 'B' ||
          lookahead == 'a' ||
          lookahead == 'b') ADVANCE(80);
      END_STATE();
    case 51:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(39);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(52);
      END_STATE();
    case 52:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 53:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 54:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 55:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(82);
      END_STATE();
    case 56:
      if (lookahead == 'P' ||
          lookahead == 'R' ||
          lookahead == 'p' ||
          lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(83);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      END_STATE();
    case 59:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '"', 86,
        '#', 9,
        '%', 50,
        '&', 75,
        '(', 71,
        ')', 72,
        '*', 78,
        '+', 68,
        ',', 65,
        '-', 69,
        '.', 38,
        '/', 79,
        '0', 81,
        ':', 64,
        '<', 6,
        '>', 7,
        '[', 66,
        ']', 67,
        '|', 74,
        '~', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(60);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_directive_name);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(63);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(55);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(57);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '/') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '/') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '\r' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_preproc_arg);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_preproc_include_token1);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_preproc_error_token1);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_preproc_define_token1);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_preproc_undef_token1);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_preproc_if_token1);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_preproc_if_token2);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_preproc_elif_token1);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_preproc_else_token1);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(1);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(2);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(3);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(4);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(5);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(6);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(7);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(8);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(9);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(10);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(11);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(12);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(13);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(14);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(16);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(18);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        'E', 23,
        'e', 23,
        'G', 24,
        'g', 24,
        'L', 25,
        'l', 25,
        'M', 26,
        'm', 26,
        'N', 27,
        'n', 27,
      );
      END_STATE();
    case 7:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(29);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(32);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(34);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(35);
      END_STATE();
    case 13:
      ADVANCE_MAP(
        'H', 36,
        'h', 36,
        'T', 22,
        't', 22,
        'U', 37,
        'u', 37,
        'W', 38,
        'w', 38,
      );
      END_STATE();
    case 14:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_mnemonic);
      END_STATE();
    case 23:
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'E' ||
          lookahead == 'T' ||
          lookahead == 'e' ||
          lookahead == 't') ADVANCE(22);
      END_STATE();
    case 25:
      if (lookahead == 'E' ||
          lookahead == 'T' ||
          lookahead == 'e' ||
          lookahead == 't') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 29:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(22);
      END_STATE();
    case 30:
      if (lookahead == 'P' ||
          lookahead == 'T' ||
          lookahead == 'p' ||
          lookahead == 't') ADVANCE(22);
      END_STATE();
    case 31:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(22);
      END_STATE();
    case 32:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 33:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'I' ||
          lookahead == 'N' ||
          lookahead == 'i' ||
          lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 36:
      if (lookahead == 'L' ||
          lookahead == 'R' ||
          lookahead == 'l' ||
          lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 37:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(22);
      END_STATE();
    case 38:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 39:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 40:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 41:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 42:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(22);
      END_STATE();
    case 43:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 44:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 45:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 46:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 60},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 60},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 60},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_mnemonic] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_directive_name] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [aux_sym_preproc_include_token1] = ACTIONS(1),
    [aux_sym_preproc_error_token1] = ACTIONS(1),
    [aux_sym_preproc_define_token1] = ACTIONS(1),
    [aux_sym_preproc_undef_token1] = ACTIONS(1),
    [aux_sym_preproc_if_token1] = ACTIONS(1),
    [aux_sym_preproc_if_token2] = ACTIONS(1),
    [aux_sym_preproc_elif_token1] = ACTIONS(1),
    [aux_sym_preproc_else_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(82),
    [sym__item] = STATE(7),
    [sym__line_content] = STATE(68),
    [sym__code_line] = STATE(68),
    [sym__statement] = STATE(68),
    [sym_label] = STATE(30),
    [sym_instruction] = STATE(68),
    [sym_directive] = STATE(68),
    [sym_preproc_include] = STATE(68),
    [sym_preproc_error] = STATE(68),
    [sym_preproc_define] = STATE(68),
    [sym_preproc_undef] = STATE(68),
    [sym_preproc_if] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym__code_line_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_mnemonic] = ACTIONS(11),
    [sym_directive_name] = ACTIONS(13),
    [aux_sym_preproc_include_token1] = ACTIONS(15),
    [aux_sym_preproc_error_token1] = ACTIONS(17),
    [aux_sym_preproc_define_token1] = ACTIONS(19),
    [aux_sym_preproc_undef_token1] = ACTIONS(21),
    [aux_sym_preproc_if_token1] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(23), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(25), 1,
      sym_newline,
    ACTIONS(27), 1,
      aux_sym_preproc_if_token2,
    ACTIONS(29), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(31), 1,
      aux_sym_preproc_else_token1,
    STATE(79), 1,
      sym_preproc_else,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(45), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(85), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [67] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(23), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(29), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(31), 1,
      aux_sym_preproc_else_token1,
    ACTIONS(33), 1,
      sym_newline,
    ACTIONS(35), 1,
      aux_sym_preproc_if_token2,
    STATE(73), 1,
      sym_preproc_else,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(46), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
    STATE(2), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(85), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [134] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(42), 1,
      sym_newline,
    ACTIONS(45), 1,
      sym_mnemonic,
    ACTIONS(48), 1,
      sym_directive_name,
    ACTIONS(51), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(54), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(57), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(60), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(63), 1,
      aux_sym_preproc_if_token1,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    ACTIONS(37), 4,
      ts_builtin_sym_end,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
    STATE(85), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [191] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(23), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(66), 1,
      sym_newline,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    ACTIONS(68), 3,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
    STATE(6), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(85), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [247] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(23), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(25), 1,
      sym_newline,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    ACTIONS(70), 3,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(85), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [303] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(23), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(25), 1,
      sym_newline,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(67), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [357] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(23), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(74), 1,
      sym_newline,
    ACTIONS(76), 1,
      aux_sym_preproc_if_token2,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(9), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(85), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [411] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(15), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(23), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(25), 1,
      sym_newline,
    ACTIONS(78), 1,
      aux_sym_preproc_if_token2,
    STATE(30), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(85), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [465] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      sym_register,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_newline,
    ACTIONS(82), 2,
      sym_number,
      sym_identifier,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    STATE(28), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
    STATE(50), 4,
      sym__operand,
      sym_direct,
      sym_indirect,
      sym_indexed,
  [502] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(92), 1,
      sym_register,
    ACTIONS(82), 2,
      sym_number,
      sym_identifier,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    STATE(28), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
    STATE(55), 4,
      sym__operand,
      sym_direct,
      sym_indirect,
      sym_indexed,
  [535] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      sym_newline,
    ACTIONS(94), 11,
      ts_builtin_sym_end,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [558] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(100), 11,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [581] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(106), 12,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_STAR,
  [602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_SLASH,
    ACTIONS(110), 12,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_STAR,
  [623] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_AMP,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(118), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(100), 6,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [652] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(118), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(100), 7,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
  [679] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(100), 9,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [704] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_SLASH,
    ACTIONS(100), 12,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_STAR,
  [725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      sym_identifier,
    ACTIONS(126), 1,
      sym_newline,
    ACTIONS(122), 11,
      ts_builtin_sym_end,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [748] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(132), 1,
      sym_newline,
    ACTIONS(128), 11,
      ts_builtin_sym_end,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(134), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [792] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(94), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [813] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(128), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(138), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [855] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    ACTIONS(142), 1,
      sym_newline,
    ACTIONS(138), 11,
      ts_builtin_sym_end,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [878] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(144), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_mnemonic,
      sym_directive_name,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [899] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_AMP,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(118), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [928] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      sym_string,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(152), 2,
      sym_number,
      sym_identifier,
    STATE(32), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [955] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_mnemonic,
    ACTIONS(13), 1,
      sym_directive_name,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      sym_newline,
    STATE(44), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(72), 3,
      sym__statement,
      sym_instruction,
      sym_directive,
  [981] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(160), 1,
      sym_register,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(158), 2,
      sym_number,
      sym_identifier,
    STATE(40), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1005] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_AMP,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(118), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1033] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(164), 2,
      sym_number,
      sym_identifier,
    STATE(13), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1054] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(166), 2,
      sym_number,
      sym_identifier,
    STATE(17), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1075] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(168), 2,
      sym_number,
      sym_identifier,
    STATE(18), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1096] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(170), 2,
      sym_number,
      sym_identifier,
    STATE(19), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1117] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_AMP,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(118), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [1144] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(174), 2,
      sym_number,
      sym_identifier,
    STATE(41), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1165] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(176), 2,
      sym_number,
      sym_identifier,
    STATE(16), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1186] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_AMP,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(178), 1,
      anon_sym_RBRACK,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(118), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [1213] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_AMP,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
    ACTIONS(114), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(118), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [1240] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(182), 2,
      sym_number,
      sym_identifier,
    STATE(14), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1261] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(86), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(184), 2,
      sym_number,
      sym_identifier,
    STATE(37), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1282] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(44), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    ACTIONS(186), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_mnemonic,
      sym_directive_name,
  [1299] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(31), 1,
      aux_sym_preproc_else_token1,
    ACTIONS(191), 1,
      aux_sym_preproc_if_token2,
    STATE(83), 1,
      sym_preproc_else,
    STATE(47), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
  [1319] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      aux_sym_preproc_if_token2,
    ACTIONS(29), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(31), 1,
      aux_sym_preproc_else_token1,
    STATE(79), 1,
      sym_preproc_else,
    STATE(47), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
  [1339] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(193), 2,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_else_token1,
    STATE(47), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
  [1354] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_identifier,
    ACTIONS(198), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_mnemonic,
      sym_directive_name,
  [1367] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_DQUOTE,
    ACTIONS(206), 1,
      sym__string_content,
    ACTIONS(208), 1,
      sym_escape_sequence,
    STATE(51), 1,
      aux_sym_string_repeat1,
  [1383] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(210), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1397] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    ACTIONS(216), 1,
      sym__string_content,
    ACTIONS(219), 1,
      sym_escape_sequence,
    STATE(51), 1,
      aux_sym_string_repeat1,
  [1413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1427] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1441] = 5,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
    ACTIONS(231), 1,
      sym__string_content,
    ACTIONS(233), 1,
      sym_escape_sequence,
    STATE(49), 1,
      aux_sym_string_repeat1,
  [1457] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1466] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_preproc_arg,
    ACTIONS(235), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1495] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_RBRACK,
    ACTIONS(245), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      sym_string,
  [1541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1557] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      sym_string,
  [1567] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
    ACTIONS(259), 1,
      sym_newline,
  [1577] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(259), 1,
      sym_newline,
  [1587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1595] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1603] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      aux_sym_preproc_if_token2,
  [1626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym_newline,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_preproc_arg,
  [1640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_newline,
  [1647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
  [1654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_identifier,
  [1661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      aux_sym_preproc_if_token2,
  [1668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_newline,
  [1675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_COLON,
  [1682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [1689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      aux_sym_preproc_if_token2,
  [1696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_preproc_arg,
  [1703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 67,
  [SMALL_STATE(4)] = 134,
  [SMALL_STATE(5)] = 191,
  [SMALL_STATE(6)] = 247,
  [SMALL_STATE(7)] = 303,
  [SMALL_STATE(8)] = 357,
  [SMALL_STATE(9)] = 411,
  [SMALL_STATE(10)] = 465,
  [SMALL_STATE(11)] = 502,
  [SMALL_STATE(12)] = 535,
  [SMALL_STATE(13)] = 558,
  [SMALL_STATE(14)] = 581,
  [SMALL_STATE(15)] = 602,
  [SMALL_STATE(16)] = 623,
  [SMALL_STATE(17)] = 652,
  [SMALL_STATE(18)] = 679,
  [SMALL_STATE(19)] = 704,
  [SMALL_STATE(20)] = 725,
  [SMALL_STATE(21)] = 748,
  [SMALL_STATE(22)] = 771,
  [SMALL_STATE(23)] = 792,
  [SMALL_STATE(24)] = 813,
  [SMALL_STATE(25)] = 834,
  [SMALL_STATE(26)] = 855,
  [SMALL_STATE(27)] = 878,
  [SMALL_STATE(28)] = 899,
  [SMALL_STATE(29)] = 928,
  [SMALL_STATE(30)] = 955,
  [SMALL_STATE(31)] = 981,
  [SMALL_STATE(32)] = 1005,
  [SMALL_STATE(33)] = 1033,
  [SMALL_STATE(34)] = 1054,
  [SMALL_STATE(35)] = 1075,
  [SMALL_STATE(36)] = 1096,
  [SMALL_STATE(37)] = 1117,
  [SMALL_STATE(38)] = 1144,
  [SMALL_STATE(39)] = 1165,
  [SMALL_STATE(40)] = 1186,
  [SMALL_STATE(41)] = 1213,
  [SMALL_STATE(42)] = 1240,
  [SMALL_STATE(43)] = 1261,
  [SMALL_STATE(44)] = 1282,
  [SMALL_STATE(45)] = 1299,
  [SMALL_STATE(46)] = 1319,
  [SMALL_STATE(47)] = 1339,
  [SMALL_STATE(48)] = 1354,
  [SMALL_STATE(49)] = 1367,
  [SMALL_STATE(50)] = 1383,
  [SMALL_STATE(51)] = 1397,
  [SMALL_STATE(52)] = 1413,
  [SMALL_STATE(53)] = 1427,
  [SMALL_STATE(54)] = 1441,
  [SMALL_STATE(55)] = 1457,
  [SMALL_STATE(56)] = 1466,
  [SMALL_STATE(57)] = 1477,
  [SMALL_STATE(58)] = 1486,
  [SMALL_STATE(59)] = 1495,
  [SMALL_STATE(60)] = 1506,
  [SMALL_STATE(61)] = 1515,
  [SMALL_STATE(62)] = 1523,
  [SMALL_STATE(63)] = 1531,
  [SMALL_STATE(64)] = 1541,
  [SMALL_STATE(65)] = 1549,
  [SMALL_STATE(66)] = 1557,
  [SMALL_STATE(67)] = 1567,
  [SMALL_STATE(68)] = 1577,
  [SMALL_STATE(69)] = 1587,
  [SMALL_STATE(70)] = 1595,
  [SMALL_STATE(71)] = 1603,
  [SMALL_STATE(72)] = 1611,
  [SMALL_STATE(73)] = 1619,
  [SMALL_STATE(74)] = 1626,
  [SMALL_STATE(75)] = 1633,
  [SMALL_STATE(76)] = 1640,
  [SMALL_STATE(77)] = 1647,
  [SMALL_STATE(78)] = 1654,
  [SMALL_STATE(79)] = 1661,
  [SMALL_STATE(80)] = 1668,
  [SMALL_STATE(81)] = 1675,
  [SMALL_STATE(82)] = 1682,
  [SMALL_STATE(83)] = 1689,
  [SMALL_STATE(84)] = 1696,
  [SMALL_STATE(85)] = 1703,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_elif, 3, 0, 10),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_elif, 4, 0, 10),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_else, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_else, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 5, 0, 10),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_if, 5, 0, 10),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 7),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 7),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 4, 0, 10),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_if, 4, 0, 10),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 6, 0, 10),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_if, 6, 0, 10),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__item, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 7, 0, 10),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_if, 7, 0, 10),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 8, 0, 10),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_if, 8, 0, 10),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operand, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__code_line, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__code_line_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__code_line_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preproc_if_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preproc_if_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 3),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, 0, 3),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 1),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_define, 2, 0, 6),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indirect, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indexed, 5, 0, 11),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_define, 3, 0, 8),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_include, 2, 0, 4),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_error, 2, 0, 5),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_undef, 2, 0, 6),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__code_line, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [281] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_z33(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "z33",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
