/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 1
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_newline = 2,
  sym_comment = 3,
  anon_sym_COLON = 4,
  anon_sym_COMMA = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_PLUS = 8,
  anon_sym_DASH = 9,
  sym_directive_name = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_TILDE = 13,
  anon_sym_PIPE = 14,
  anon_sym_AMP = 15,
  anon_sym_LT_LT = 16,
  anon_sym_GT_GT = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  sym_register = 20,
  sym_number = 21,
  anon_sym_DQUOTE = 22,
  sym__string_content = 23,
  sym_escape_sequence = 24,
  sym_preproc_arg = 25,
  aux_sym_preproc_include_token1 = 26,
  aux_sym_preproc_error_token1 = 27,
  aux_sym_preproc_define_token1 = 28,
  aux_sym_preproc_undef_token1 = 29,
  aux_sym_preproc_if_token1 = 30,
  aux_sym_preproc_if_token2 = 31,
  aux_sym_preproc_elif_token1 = 32,
  aux_sym_preproc_else_token1 = 33,
  sym_source_file = 34,
  sym__item = 35,
  sym__line_content = 36,
  sym__code_line = 37,
  sym__statement = 38,
  sym_label = 39,
  sym_instruction = 40,
  sym__operand = 41,
  sym_direct = 42,
  sym_indirect = 43,
  sym_indexed = 44,
  sym_directive = 45,
  sym__expression = 46,
  sym_parenthesized_expression = 47,
  sym_unary_expression = 48,
  sym_binary_expression = 49,
  sym_string = 50,
  sym_preproc_include = 51,
  sym_preproc_error = 52,
  sym_preproc_define = 53,
  sym_preproc_undef = 54,
  sym_preproc_if = 55,
  sym_preproc_elif = 56,
  sym_preproc_else = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym__code_line_repeat1 = 59,
  aux_sym_instruction_repeat1 = 60,
  aux_sym_string_repeat1 = 61,
  aux_sym_preproc_if_repeat1 = 62,
  alias_sym_mnemonic = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_directive_name] = "directive_name",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_TILDE] = "~",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_register] = "register",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_content] = "_string_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_preproc_arg] = "preproc_arg",
  [aux_sym_preproc_include_token1] = "preproc_directive",
  [aux_sym_preproc_error_token1] = "preproc_directive",
  [aux_sym_preproc_define_token1] = "preproc_directive",
  [aux_sym_preproc_undef_token1] = "preproc_directive",
  [aux_sym_preproc_if_token1] = "preproc_directive",
  [aux_sym_preproc_if_token2] = "preproc_directive",
  [aux_sym_preproc_elif_token1] = "preproc_directive",
  [aux_sym_preproc_else_token1] = "preproc_directive",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym__line_content] = "_line_content",
  [sym__code_line] = "_code_line",
  [sym__statement] = "_statement",
  [sym_label] = "label",
  [sym_instruction] = "instruction",
  [sym__operand] = "_operand",
  [sym_direct] = "direct",
  [sym_indirect] = "indirect",
  [sym_indexed] = "indexed",
  [sym_directive] = "directive",
  [sym__expression] = "_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [sym_preproc_include] = "preproc_include",
  [sym_preproc_error] = "preproc_error",
  [sym_preproc_define] = "preproc_define",
  [sym_preproc_undef] = "preproc_undef",
  [sym_preproc_if] = "preproc_if",
  [sym_preproc_elif] = "preproc_elif",
  [sym_preproc_else] = "preproc_else",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__code_line_repeat1] = "_code_line_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_preproc_if_repeat1] = "preproc_if_repeat1",
  [alias_sym_mnemonic] = "mnemonic",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_directive_name] = sym_directive_name,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_register] = sym_register,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_content] = sym__string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_preproc_arg] = sym_preproc_arg,
  [aux_sym_preproc_include_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_error_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_define_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_undef_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_if_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_if_token2] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_elif_token1] = aux_sym_preproc_include_token1,
  [aux_sym_preproc_else_token1] = aux_sym_preproc_include_token1,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym__line_content] = sym__line_content,
  [sym__code_line] = sym__code_line,
  [sym__statement] = sym__statement,
  [sym_label] = sym_label,
  [sym_instruction] = sym_instruction,
  [sym__operand] = sym__operand,
  [sym_direct] = sym_direct,
  [sym_indirect] = sym_indirect,
  [sym_indexed] = sym_indexed,
  [sym_directive] = sym_directive,
  [sym__expression] = sym__expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [sym_preproc_include] = sym_preproc_include,
  [sym_preproc_error] = sym_preproc_error,
  [sym_preproc_define] = sym_preproc_define,
  [sym_preproc_undef] = sym_preproc_undef,
  [sym_preproc_if] = sym_preproc_if,
  [sym_preproc_elif] = sym_preproc_elif,
  [sym_preproc_else] = sym_preproc_else,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__code_line_repeat1] = aux_sym__code_line_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_preproc_if_repeat1] = aux_sym_preproc_if_repeat1,
  [alias_sym_mnemonic] = alias_sym_mnemonic,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_include_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_error_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_define_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_undef_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_if_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_if_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_elif_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_preproc_else_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym__line_content] = {
    .visible = false,
    .named = true,
  },
  [sym__code_line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym__operand] = {
    .visible = false,
    .named = true,
  },
  [sym_direct] = {
    .visible = true,
    .named = true,
  },
  [sym_indirect] = {
    .visible = true,
    .named = true,
  },
  [sym_indexed] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_include] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_error] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_define] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_undef] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_if] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_elif] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_else] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__code_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preproc_if_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_mnemonic] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_condition = 2,
  field_left = 3,
  field_message = 4,
  field_mnemonic = 5,
  field_name = 6,
  field_operand = 7,
  field_operator = 8,
  field_path = 9,
  field_right = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_condition] = "condition",
  [field_left] = "left",
  [field_message] = "message",
  [field_mnemonic] = "mnemonic",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_path] = "path",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 3},
  [10] = {.index = 14, .length = 1},
  [11] = {.index = 15, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_mnemonic, 0},
  [1] =
    {field_argument, 1},
    {field_name, 0},
  [3] =
    {field_name, 0},
  [4] =
    {field_path, 1},
  [5] =
    {field_message, 1},
  [6] =
    {field_name, 1},
  [7] =
    {field_operand, 1},
    {field_operator, 0},
  [9] =
    {field_name, 1},
    {field_value, 2},
  [11] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [14] =
    {field_condition, 1},
  [15] =
    {field_operator, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_mnemonic,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '"', 86,
        '#', 9,
        '%', 50,
        '&', 75,
        '(', 71,
        ')', 72,
        '*', 78,
        '+', 68,
        ',', 65,
        '-', 69,
        '.', 38,
        '/', 79,
        '0', 81,
        ':', 64,
        '<', 6,
        '>', 7,
        '[', 66,
        '\\', 3,
        ']', 67,
        '|', 74,
        '~', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(91);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(86);
      if (lookahead == '/') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(90);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(76);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(77);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(98);
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(100);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(99);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(21);
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 37:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(93);
      END_STATE();
    case 38:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(43);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(51);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(49);
      END_STATE();
    case 39:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(80);
      END_STATE();
    case 41:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 42:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(70);
      END_STATE();
    case 43:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 44:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(53);
      END_STATE();
    case 45:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 46:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 48:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 49:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(40);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(56);
      if (lookahead == 'A' ||
          lookahead == 'B' ||
          lookahead == 'a' ||
          lookahead == 'b') ADVANCE(80);
      END_STATE();
    case 51:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(39);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(52);
      END_STATE();
    case 52:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 53:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 54:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 55:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(82);
      END_STATE();
    case 56:
      if (lookahead == 'P' ||
          lookahead == 'R' ||
          lookahead == 'p' ||
          lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(83);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      END_STATE();
    case 59:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '"', 86,
        '#', 9,
        '%', 50,
        '&', 75,
        '(', 71,
        ')', 72,
        '*', 78,
        '+', 68,
        ',', 65,
        '-', 69,
        '.', 38,
        '/', 79,
        '0', 81,
        ':', 64,
        '<', 6,
        '>', 7,
        '[', 66,
        ']', 67,
        '|', 74,
        '~', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(59);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(60);
      if (lookahead != 0) ADVANCE(93);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_directive_name);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(63);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(55);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(57);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '/') ADVANCE(88);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '/') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '\r' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_preproc_arg);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_preproc_include_token1);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_preproc_error_token1);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_preproc_define_token1);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_preproc_undef_token1);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_preproc_if_token1);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_preproc_if_token2);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_preproc_elif_token1);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_preproc_else_token1);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 60},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 60},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 60},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_directive_name] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [aux_sym_preproc_include_token1] = ACTIONS(1),
    [aux_sym_preproc_error_token1] = ACTIONS(1),
    [aux_sym_preproc_define_token1] = ACTIONS(1),
    [aux_sym_preproc_undef_token1] = ACTIONS(1),
    [aux_sym_preproc_if_token1] = ACTIONS(1),
    [aux_sym_preproc_if_token2] = ACTIONS(1),
    [aux_sym_preproc_elif_token1] = ACTIONS(1),
    [aux_sym_preproc_else_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(82),
    [sym__item] = STATE(7),
    [sym__line_content] = STATE(70),
    [sym__code_line] = STATE(70),
    [sym__statement] = STATE(70),
    [sym_label] = STATE(39),
    [sym_instruction] = STATE(70),
    [sym_directive] = STATE(70),
    [sym_preproc_include] = STATE(70),
    [sym_preproc_error] = STATE(70),
    [sym_preproc_define] = STATE(70),
    [sym_preproc_undef] = STATE(70),
    [sym_preproc_if] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym__code_line_repeat1] = STATE(39),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_directive_name] = ACTIONS(11),
    [aux_sym_preproc_include_token1] = ACTIONS(13),
    [aux_sym_preproc_error_token1] = ACTIONS(15),
    [aux_sym_preproc_define_token1] = ACTIONS(17),
    [aux_sym_preproc_undef_token1] = ACTIONS(19),
    [aux_sym_preproc_if_token1] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(15), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(23), 1,
      sym_newline,
    ACTIONS(25), 1,
      aux_sym_preproc_if_token2,
    ACTIONS(27), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(29), 1,
      aux_sym_preproc_else_token1,
    STATE(80), 1,
      sym_preproc_else,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(45), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(84), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [64] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(15), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(27), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(29), 1,
      aux_sym_preproc_else_token1,
    ACTIONS(31), 1,
      sym_newline,
    ACTIONS(33), 1,
      aux_sym_preproc_if_token2,
    STATE(73), 1,
      sym_preproc_else,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(44), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
    STATE(2), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(84), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [128] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(40), 1,
      sym_newline,
    ACTIONS(43), 1,
      sym_directive_name,
    ACTIONS(46), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(49), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(52), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(55), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(58), 1,
      aux_sym_preproc_if_token1,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
    STATE(84), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [182] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(15), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(23), 1,
      sym_newline,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    ACTIONS(61), 3,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(84), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [235] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(15), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(63), 1,
      sym_newline,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    ACTIONS(65), 3,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
    STATE(5), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(84), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [288] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(15), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(23), 1,
      sym_newline,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(68), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [339] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(15), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(69), 1,
      sym_newline,
    ACTIONS(71), 1,
      aux_sym_preproc_if_token2,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(9), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(84), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [390] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(13), 1,
      aux_sym_preproc_include_token1,
    ACTIONS(15), 1,
      aux_sym_preproc_error_token1,
    ACTIONS(17), 1,
      aux_sym_preproc_define_token1,
    ACTIONS(19), 1,
      aux_sym_preproc_undef_token1,
    ACTIONS(21), 1,
      aux_sym_preproc_if_token1,
    ACTIONS(23), 1,
      sym_newline,
    ACTIONS(73), 1,
      aux_sym_preproc_if_token2,
    STATE(39), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(4), 3,
      sym__item,
      sym_preproc_if,
      aux_sym_source_file_repeat1,
    STATE(84), 9,
      sym__line_content,
      sym__code_line,
      sym__statement,
      sym_instruction,
      sym_directive,
      sym_preproc_include,
      sym_preproc_error,
      sym_preproc_define,
      sym_preproc_undef,
  [441] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_COLON,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      sym_register,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym_newline,
    ACTIONS(77), 2,
      sym_number,
      sym_identifier,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    STATE(29), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
    STATE(54), 4,
      sym__operand,
      sym_direct,
      sym_indirect,
      sym_indexed,
  [481] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_register,
    ACTIONS(77), 2,
      sym_number,
      sym_identifier,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    STATE(29), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
    STATE(58), 4,
      sym__operand,
      sym_direct,
      sym_indirect,
      sym_indexed,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(91), 12,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_STAR,
  [535] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(95), 12,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_STAR,
  [556] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(99), 11,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [579] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_AMP,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(99), 6,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [608] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
  [635] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(99), 9,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [660] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_SLASH,
    ACTIONS(99), 12,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_STAR,
  [681] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_newline,
    ACTIONS(113), 11,
      ts_builtin_sym_end,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [701] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [719] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [737] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_newline,
    ACTIONS(117), 11,
      ts_builtin_sym_end,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [757] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [775] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_newline,
    ACTIONS(123), 11,
      ts_builtin_sym_end,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 12,
      ts_builtin_sym_end,
      sym_newline,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [831] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_newline,
    ACTIONS(129), 11,
      ts_builtin_sym_end,
      sym_directive_name,
      sym_identifier,
      aux_sym_preproc_include_token1,
      aux_sym_preproc_error_token1,
      aux_sym_preproc_define_token1,
      aux_sym_preproc_undef_token1,
      aux_sym_preproc_if_token1,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_elif_token1,
      aux_sym_preproc_else_token1,
  [851] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_string,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(133), 2,
      sym_number,
      sym_identifier,
    STATE(30), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [878] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_AMP,
    ACTIONS(139), 1,
      anon_sym_PIPE,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [907] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_AMP,
    ACTIONS(139), 1,
      anon_sym_PIPE,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym_newline,
  [935] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_register,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(143), 2,
      sym_number,
      sym_identifier,
    STATE(34), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [959] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(147), 2,
      sym_number,
      sym_identifier,
    STATE(35), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [980] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_AMP,
    ACTIONS(139), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [1007] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_AMP,
    ACTIONS(139), 1,
      anon_sym_PIPE,
    ACTIONS(151), 1,
      anon_sym_RBRACK,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [1034] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_AMP,
    ACTIONS(139), 1,
      anon_sym_PIPE,
    ACTIONS(153), 1,
      anon_sym_RBRACK,
    ACTIONS(105), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(109), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [1061] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(155), 2,
      sym_number,
      sym_identifier,
    STATE(13), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1082] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(157), 2,
      sym_number,
      sym_identifier,
    STATE(33), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1103] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(159), 2,
      sym_number,
      sym_identifier,
    STATE(16), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1124] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_directive_name,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      sym_newline,
    STATE(46), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    STATE(63), 3,
      sym__statement,
      sym_instruction,
      sym_directive,
  [1147] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(163), 2,
      sym_number,
      sym_identifier,
    STATE(17), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1168] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(165), 2,
      sym_number,
      sym_identifier,
    STATE(14), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1189] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(167), 2,
      sym_number,
      sym_identifier,
    STATE(15), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1210] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 2,
      anon_sym_DASH,
      anon_sym_TILDE,
    ACTIONS(169), 2,
      sym_number,
      sym_identifier,
    STATE(18), 4,
      sym__expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
  [1231] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      aux_sym_preproc_if_token2,
    ACTIONS(27), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(29), 1,
      aux_sym_preproc_else_token1,
    STATE(80), 1,
      sym_preproc_else,
    STATE(47), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
  [1251] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(29), 1,
      aux_sym_preproc_else_token1,
    ACTIONS(171), 1,
      aux_sym_preproc_if_token2,
    STATE(81), 1,
      sym_preproc_else,
    STATE(47), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
  [1271] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(46), 2,
      sym_label,
      aux_sym__code_line_repeat1,
    ACTIONS(173), 3,
      ts_builtin_sym_end,
      sym_newline,
      sym_directive_name,
  [1287] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      aux_sym_preproc_elif_token1,
    ACTIONS(178), 2,
      aux_sym_preproc_if_token2,
      aux_sym_preproc_else_token1,
    STATE(47), 2,
      sym_preproc_elif,
      aux_sym_preproc_if_repeat1,
  [1302] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1316] = 5,
    ACTIONS(187), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(191), 1,
      sym__string_content,
    ACTIONS(193), 1,
      sym_escape_sequence,
    STATE(50), 1,
      aux_sym_string_repeat1,
  [1332] = 5,
    ACTIONS(187), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
    ACTIONS(197), 1,
      sym__string_content,
    ACTIONS(200), 1,
      sym_escape_sequence,
    STATE(50), 1,
      aux_sym_string_repeat1,
  [1348] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1362] = 5,
    ACTIONS(187), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
    ACTIONS(210), 1,
      sym__string_content,
    ACTIONS(212), 1,
      sym_escape_sequence,
    STATE(49), 1,
      aux_sym_string_repeat1,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 4,
      ts_builtin_sym_end,
      sym_newline,
      sym_directive_name,
      sym_identifier,
  [1388] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(216), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1420] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_preproc_arg,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_COMMA,
  [1449] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
    ACTIONS(230), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1492] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1500] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    STATE(72), 1,
      sym_string,
  [1510] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      sym_string,
  [1520] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
    ACTIONS(242), 1,
      sym_newline,
  [1530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1538] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(242), 1,
      sym_newline,
  [1548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      sym_newline,
  [1564] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      aux_sym_preproc_if_token2,
  [1571] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_preproc_arg,
  [1578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_newline,
  [1585] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_newline,
  [1592] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_preproc_arg,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_newline,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      sym_identifier,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      aux_sym_preproc_if_token2,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      aux_sym_preproc_if_token2,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      ts_builtin_sym_end,
  [1634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_identifier,
  [1641] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      sym_newline,
  [1648] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 64,
  [SMALL_STATE(4)] = 128,
  [SMALL_STATE(5)] = 182,
  [SMALL_STATE(6)] = 235,
  [SMALL_STATE(7)] = 288,
  [SMALL_STATE(8)] = 339,
  [SMALL_STATE(9)] = 390,
  [SMALL_STATE(10)] = 441,
  [SMALL_STATE(11)] = 481,
  [SMALL_STATE(12)] = 514,
  [SMALL_STATE(13)] = 535,
  [SMALL_STATE(14)] = 556,
  [SMALL_STATE(15)] = 579,
  [SMALL_STATE(16)] = 608,
  [SMALL_STATE(17)] = 635,
  [SMALL_STATE(18)] = 660,
  [SMALL_STATE(19)] = 681,
  [SMALL_STATE(20)] = 701,
  [SMALL_STATE(21)] = 719,
  [SMALL_STATE(22)] = 737,
  [SMALL_STATE(23)] = 757,
  [SMALL_STATE(24)] = 775,
  [SMALL_STATE(25)] = 795,
  [SMALL_STATE(26)] = 813,
  [SMALL_STATE(27)] = 831,
  [SMALL_STATE(28)] = 851,
  [SMALL_STATE(29)] = 878,
  [SMALL_STATE(30)] = 907,
  [SMALL_STATE(31)] = 935,
  [SMALL_STATE(32)] = 959,
  [SMALL_STATE(33)] = 980,
  [SMALL_STATE(34)] = 1007,
  [SMALL_STATE(35)] = 1034,
  [SMALL_STATE(36)] = 1061,
  [SMALL_STATE(37)] = 1082,
  [SMALL_STATE(38)] = 1103,
  [SMALL_STATE(39)] = 1124,
  [SMALL_STATE(40)] = 1147,
  [SMALL_STATE(41)] = 1168,
  [SMALL_STATE(42)] = 1189,
  [SMALL_STATE(43)] = 1210,
  [SMALL_STATE(44)] = 1231,
  [SMALL_STATE(45)] = 1251,
  [SMALL_STATE(46)] = 1271,
  [SMALL_STATE(47)] = 1287,
  [SMALL_STATE(48)] = 1302,
  [SMALL_STATE(49)] = 1316,
  [SMALL_STATE(50)] = 1332,
  [SMALL_STATE(51)] = 1348,
  [SMALL_STATE(52)] = 1362,
  [SMALL_STATE(53)] = 1378,
  [SMALL_STATE(54)] = 1388,
  [SMALL_STATE(55)] = 1402,
  [SMALL_STATE(56)] = 1411,
  [SMALL_STATE(57)] = 1420,
  [SMALL_STATE(58)] = 1431,
  [SMALL_STATE(59)] = 1440,
  [SMALL_STATE(60)] = 1449,
  [SMALL_STATE(61)] = 1460,
  [SMALL_STATE(62)] = 1468,
  [SMALL_STATE(63)] = 1476,
  [SMALL_STATE(64)] = 1484,
  [SMALL_STATE(65)] = 1492,
  [SMALL_STATE(66)] = 1500,
  [SMALL_STATE(67)] = 1510,
  [SMALL_STATE(68)] = 1520,
  [SMALL_STATE(69)] = 1530,
  [SMALL_STATE(70)] = 1538,
  [SMALL_STATE(71)] = 1548,
  [SMALL_STATE(72)] = 1556,
  [SMALL_STATE(73)] = 1564,
  [SMALL_STATE(74)] = 1571,
  [SMALL_STATE(75)] = 1578,
  [SMALL_STATE(76)] = 1585,
  [SMALL_STATE(77)] = 1592,
  [SMALL_STATE(78)] = 1599,
  [SMALL_STATE(79)] = 1606,
  [SMALL_STATE(80)] = 1613,
  [SMALL_STATE(81)] = 1620,
  [SMALL_STATE(82)] = 1627,
  [SMALL_STATE(83)] = 1634,
  [SMALL_STATE(84)] = 1641,
  [SMALL_STATE(85)] = 1648,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_elif, 4, 0, 10),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_elif, 3, 0, 10),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_else, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_else, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 7),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 7),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 9),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 4, 0, 10),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 5, 0, 10),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 6, 0, 10),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 8, 0, 10),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_if, 7, 0, 10),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__operand, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__code_line, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__code_line_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__code_line_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preproc_if_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preproc_if_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 3),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indirect, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_define, 2, 0, 6),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indexed, 5, 0, 11),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_undef, 2, 0, 6),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__code_line, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_define, 3, 0, 8),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_include, 2, 0, 4),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_error, 2, 0, 5),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [264] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_z33(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "z33",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 8,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
