# $schema: https://www.schemastore.org/pnpm-workspace.json

packages:
  - web
  - vscode

ignoredBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - msw
onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - keytar

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@5.7.2
  - semver@6.3.1
  - reselect@5.1.1
