# $schema: https://www.schemastore.org/pnpm-workspace.json

packages:
  - web
  - vscode
  - tree-sitter-z33

ignoredBuiltDependencies:
  - esbuild
  - msw

onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - keytar
  - tree-sitter-cli

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver
  - reselect@5.1.1
