# $schema: https://www.schemastore.org/pnpm-workspace.json

packages:
  - editors/web
  - editors/vscode
  - tree-sitter-z33

catalog:
  wasm-pack: ^0.15.0
  oxlint: ^1.72.0
  oxfmt: ^0.58.0
  typescript: 6.0.3

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - keytar
  - tree-sitter-cli
  - wasm-pack

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver
  - reselect@5.1.1
